numerapi_configs:
  numerai_public_id: numerapiPublicID
  numerai_secret: numerapiSecret
  model_name: cttsai
online_diagnostics: null
offline_diagnostics:
  - script_type: python
    script_file: ./offline_model_diagnostics.py
compute:
  - command:
      - --compute-eval
    config_file: null
    refresh_level: predictions
    script_file: ./ensemble.py
    script_type: python
preprocess: null
closure:
  - script_file: ./offline_model_overview.py
    script_type: python
